#!/bin/sh
#
# $Id$
#
# renderQueued	initscript for townguide renderQueue.py
#		This file should be placed in /etc/init.d.
#
# Original Author: Graham Jones
#

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="renderQueue townguide job queue manager"
NAME=renderQueue.py
DAEMON=/home/disk2/www/townguide/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
USER=www
LOGDIR=/var/log/$NAME/

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
	. /etc/default/$NAME
fi

#
#	Function that starts the daemon/service.
#
d_start() {
	start-stop-daemon --start --quiet \
                --chuid $USER \
                --pidfile $PIDFILE \
		--exec $DAEMON \
                -- \
                --pidfile $PIDFILE \
                --daemon \
                --logdir $LOGDIR 
	
}
#	Function that stops the daemon/service.
#
d_stop() {

	## This is a bug in the start-stop-daemon that checks the PID name from the /proc/PID/stat filesystem...
	## Unfortunately this cuts-off the name of the daemon because its longer now, and then it doesnt get 
	## caught by the start-stop-daemon. The daemon actually reports it as squeezecenter_s instead of 
	## squeezecenter_safe.
	start-stop-daemon -o --stop --pidfile $PIDFILE --name renderQueue
}

#
#	Function that sends a SIGHUP to the daemon/service.
#
d_reload() {
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--name $NAME --signal 1
}

case "$1" in
  start)
	echo -n "Starting $DESC"
	d_start
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC"
	d_stop
	echo "."
	;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $NAME"
	d_stop
	sleep 1
	d_start
	echo "."
	;;
  *)
	# echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
